routes/web.php
<?php

use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('discussions', 'DiscussionsController');
Route::resource('disuccsions/{discussion}/replies', 'RepliesController');

Route::get('users/notifications', [UsersController::class, 'notifications'])->name('users.notifications');
Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@reply')->name('discussions.best-reply');

app/Discussion.php
<?php

namespace App;

use App\Notifications\ReplyMarkedAsBestReply;

class Discussion extends Model
{
    public function author()
    {
        // If change the Model Name then use field name 
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function markAsBestReply(Reply $reply)
    {
        $this->update([
            'reply_id'  =>  $reply->id
        ]);

        if ($reply->owner->id == $this->author->id) {
            return;
        }

        $reply->owner->notify(new ReplyMarkedAsBestReply($reply->discussion));
    }

    // public function getBestReply()
    // {
    //     return $this->Reply::find($this->reply_id);
    // }

    public function bestReply()
    {
        return $this->belongsTo(Reply::class, 'reply_id');
    }

    public function scopeFilterByChannels($builder)
    {
        if (request()->query('channel')) {
            // filter
            $channel = Channel::where('slug', request()->query('channel'))->first();

            if ($channel) {
                return $builder->where('channel_id', $channel->id);
            }

            return $builder;
        }

        return $builder;
    }
}

app/Http/Controllers/DiscussionsController.php
<?php

namespace App\Http\Controllers;

use App\Discussion;
use App\Http\Requests\CreateDiscussionRequest;
use App\Reply;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class DiscussionsController extends Controller
{
    /**
     * Non authorized user cannot access this route
     *
     */
    public function __construct()
    {
        $this->middleware(['auth', 'verified'])->only(['create', 'store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('discussions.index', [
            // Remove scope when use
            'discussions'   => Discussion::filterByChannels()->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('discussions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDiscussionRequest $request)
    {
        /*Discussion::create([
            'title'         => $request->title,
            'content'       => $request->content,
            'channel_id'    => $request->channel
        ]);*/

        auth()->user()->discussions()->create([
            'title'         => $request->title,
            'content'       => $request->content,
            'channel_id'    => $request->channel,
            'slug'          => Str::slug($request->title)
        ]);

        session()->flash('success', 'Discussion Posted');

        return redirect()->route('discussions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Discussion $discussion)
    {
        return view('discussions.show', compact('discussion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function reply(Discussion $discussion, Reply $reply)
    {
        $discussion->markAsBestReply($reply);

        session()->flash('success', 'Mark as Best Reply');

        return redirect()->back();
    }
}

resources/views/discussions/create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-12">
    <div class="card">
        <div class="card-header">Add Discussion</div>

        <div class="card-body">
        <form action="{{ route('discussions.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" id="title" value="">
            </div>
            
            <div class="form-group">
              <label for="content">Content</label>
              <input id="content" type="hidden" name="content">
              <trix-editor input="content"></trix-editor>
            </div>

            <div class="form-group">
              <label for="channel">Channel</label>
              <select class="form-control" name="channel" id="channel">
                @foreach ($channels as $channel)
                    <option value="{{ $channel->id }}">{{ $channel->name }}</option>
                @endforeach
              </select>
            </div>
            <button type="submit" class="btn btn-success">Create Discussion</button>
        </form>
        </div>
    </div>
</div>
@endsection

resources/views/discussions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
    @if (session('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
    @endif
</div>

<div class="col-md-12">
    @foreach ($discussions as $discussion)
    <div class="card mb-2">
        @include('partials.discussion-header')
        <div class="card-body">
            <div class="text-center">
                <strong> {{ $discussion->title }}</strong>
            </div>
        </div>
    </div>
    @endforeach
    {{ $discussions->appends(['channel' => request()->query('channel')])->links() }}
</div>
@endsection

resources/views/discussions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-md-12">
    @if (session('success'))
        <div class="alert alert-success" role="alert">
            {{ session('success') }}
        </div>
    @endif
</div>
<div class="col-md-12">
    <div class="card mb-2">
        @include('partials.discussion-header')
        <div class="card-body">
            <div class="text-center">
                <strong> {{ $discussion->title }}</strong>
            </div>
            <hr/>
            {!! $discussion->content !!}
            @if($discussion->bestReply)
                <div class="card bg-success mt-2">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <div>
                                <img width="30px" height="30px" style="border-radius: 50%" src="{{ Gravatar::src($discussion->bestReply->owner->email) }}" alt="">
                                <strong class="ml-2">{{ $discussion->bestReply->owner->name }}</strong>
                            </div>
                            <div>BEST REPLY</div>
                        </div>
                    </div>
                    <div class="card-body">
                        {!! $discussion->bestReply->content !!}
                    </div>
                </div>
            @endif
        </div>
    </div>
    
    <p class="text-info">Replies</p>
    <hr/>
    @foreach($discussion->replies()->paginate(3) as $reply)
        <div class="card mb-1">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <div>
                        <img width="30px" height="30px" style="border-radius: 50%" src="{{ Gravatar::src($reply->owner->email) }}" alt=""/>
                        <strong class="ml-2">{{ $reply->owner->name }}</strong>
                    </div>
                    <div>
                        @auth
                            @if(auth()->user()->id === $discussion->user_id)
                            <form action="{{ route('discussions.best-reply', ['discussion' => $discussion->slug, 'reply' => $reply->id ]) }}" method="POST">
                                @csrf 
                                <button type="submit" class="btn btn-sm btn-primary">Mark as best reply</button>
                            </form>
                            @endif
                        @endauth
                    </div>
                </div>
            </div>
            <div class="card-body">
                {!! $reply->content !!}
            </div>
        </div>
    @endforeach 
        {{ $discussion->replies()->paginate(3)->links() }}

    <div class="card mt-2">
        <div class="card-header">Add a reply</div>
        <div class="card-body">
            @auth
                <form action="{{ route('replies.store', $discussion->slug) }}" method="POST">
                    @csrf
                    <input type="hidden" name="content" id="content">
                    <trix-editor input="content"></trix-editor>
                    <button type="submit" class="btn btn-success mt-2">Add Reply</button>
                </form>
            @else
                <a href="{{ route('login') }}" class="btn btn-info text-center">Sign In to Add Reply</a>    
            @endauth
        </div>
    </div>    
</div>
@endsection